version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME=localhost"
      - "KAFKA_CREATE_TOPICS=test:1:1"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - "9042:9042"

  postgres:
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"